services:
  wireguard-dashboard-fix:
    #image: donaldzou/wgdashboard:latest
    build: .
    restart: unless-stopped
    container_name: wgdashboard-fix
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
    #Use Ofuscated Wireguard (AmneziaWG)
      - AMNEZIA_WG=true
    #Set Timezone
      - TZ=America/Chicago

    #Tor Settings
    ##########################################################
      - WGD_TOR_PROXY=true
      - WGD_TOR_EXIT_NODES={ch}
      - WGD_TOR_DNS_EXIT_NODES={us}
      - WGD_TOR_PLUGIN=webtunnel #OPTIONS webtunnel, obfs4, snowflake
      - WGD_TOR_BRIDGES=false

    #WGDashboard Global Settings
    ##########################################################
      - WGD_WELCOME_SESSION=false
      - WGD_AUTH_REQ=false
      - WGD_USER=admin
      - WGD_PASS=admin
      - WGD_REMOTE_ENDPOINT=192.168.0.9
      - WGD_REMOTE_ENDPOINT_PORT=80
      - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0
      - WGD_KEEP_ALIVE=21
      - WGD_MTU=1420
      - WGD_PORT_RANGE_STARTPORT=4430

    #DNS Setiings (Set To use Containers Above) You can use your own DNS
    ##########################################################
      - WGD_DNS="1.1.1.1, 1.0.0.1"
      - WGD_IPTABLES_DNS=1.1.1.1

      
    #Obfuscated Wireguard via AmneziaWG Junk Headder Settings
    #All parameters should be the same between Client and Server, except Jc - it can vary.
    #########################################################
      - WGD_JC=5 #Jc — 1 ≤ Jc ≤ 128; recommended range is from 3 to 10 inclusive
      - WGD_JMIN=500 #Jmin — Jmin < Jmax; recommended value is 50
      - WGD_JMAX=550 #Jmax — Jmin < Jmax ≤ 1280; recommended value is 1000
      - WGD_S1=30 #S1 — S1 < 1280; S1 + 56 ≠ S2; recommended range is from 15 to 150 inclusive
      - WGD_S2=40 #S2 — S2 < 1280; recommended range is from 15 to 150 inclusive
      - WGD_H1=123456 #H1/H2/H3/H4 — must be unique among each other; recommended range is from 5 to 2147483647 inclusive
      - WGD_H2=67543 #H2
      - WGD_H3=32345 #H3
      - WGD_H4=123123 #H4
    ports:
      - 10086:80/tcp
      - "4430-4433:4430-4433/udp"
    #volumes:
      #- conf:/etc/wireguard
      #- data:/data

#volumes:
  #conf:
  #data:
